// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VibeCheck.Server.Data;

#nullable disable

namespace VibeCheck.Server.Migrations
{
    [DbContext(typeof(VibeCheckDbContext))]
    partial class VibeCheckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VibeCheck.Server.Models.Places", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pl_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("pl_latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("pl_longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pl_name");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("float")
                        .HasColumnName("pl_radius");

                    b.HasKey("Id");

                    b.ToTable("tbl_places");
                });

            modelBuilder.Entity("VibeCheck.Server.Models.Presence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pr_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2")
                        .HasColumnName("pr_timestamp");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int")
                        .HasColumnName("pr_place");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pr_sessionId");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("tbl_presence");
                });

            modelBuilder.Entity("VibeCheck.Server.Models.Presence", b =>
                {
                    b.HasOne("VibeCheck.Server.Models.Places", "Place")
                        .WithMany("Presences")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("VibeCheck.Server.Models.Places", b =>
                {
                    b.Navigation("Presences");
                });
#pragma warning restore 612, 618
        }
    }
}
